# https://github.com/openai/openai-python
# https://anaconda.org/conda-forge/openai
# https://anaconda.org/conda-forge/python-dotenv

name: openai-playground
channels:
  - conda-forge
dependencies:
  - python=3.7.12
  - pip=22.0.2
  - black=22.3.0
  - isort=5.10.1
  - openai=0.25.0
  - python-dotenv=0.21.0
  - python-slugify=6.1.2
